Test travis config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,7 +2,32 @@ language: csharp
 dotnet: 2.2
 sudo: required
 solution: VerifyWorldHolidays.sln
-script:
- - dotnet restore
- - msbuild /p:Configuration=Release solution-name.sln
- - mono ./HoliDayDateTest/bin/netcoreapp2.2/HoliDayDateTest.dll
+#!/usr/bin/env bash
+
+#exit if any command fails
+set -e
+
+artifactsFolder="./artifacts"
+
+if [ -d $artifactsFolder ]; then
+  rm -R $artifactsFolder
+fi
+
+dotnet restore
+
+# Ideally we would use the 'dotnet test' command to test netcoreapp and net451 so restrict for now 
+# but this currently doesn't work due to https://github.com/dotnet/cli/issues/3073 so restrict to netcoreapp
+
+dotnet test ./test/HoliDayDateTest -c Release -f netcoreapp2.2
+
+# Instead, run directly with mono for the full .net version 
+dotnet build ./test/HoliDayDateTest -c Release -f net451
+
+mono \
+./test/HoliDayDateTest/bin/Release/net451/*/dotnet-test-nunit.exe \
+./test/HoliDayDateTest/bin/Release/net451/*/TEST_PROJECT_NAME.dll
+
+revision=${TRAVIS_JOB_ID:=1}
+revision=$(printf "%04d" $revision) 
+
+dotnet pack ./src/HoliDayDate -c Release -o ./artifacts --version-suffix=$revision
